<?php
$social_networks = array(
//	name          => array(title,           url-format )
	'_43things'    => array('43Things',     'http://www.43things.com/person/%s'),
	'bebo'        => array('Bebo',          'http://www.bebo.com/Profile.jsp?MemberId=%s'),
	'catster'     => array('Catster',       'http://www.catster.com/cats/%s'),
	'delicious'   => array('del.icio.us',   'http://del.icio.us/%s/'),
	'digg'        => array('Digg',          'http://digg.com/users/%s/'),
	'dodgeball'   => array('Dodgeball',     'http://www.dodgeball.com/user?uid=%s'),
	'dogster'     => array('Dogster',       'http://www.dogster.com/dogs/%s'),
	'dopplr'      => array('Dopplr',        'http://www.dopplr.com/traveller/%s'),
	'facebook'    => array('Facebook',      'http://www.facebook.com/profile.php?id=%s'),
	'flickr'      => array('Flickr',        'http://flickr.com/photos/%s/'),
	'friendfeed'  => array('FriendFeed',    'http://friendfeed.com/%s'),
	'goodreads'   => array('GoodReads',     'http://www.goodreads.com/user/show/%s'),
	'google'      => array('Google',        'http://code.google.com/u/%s/'),
	'hi5'         => array('Hi5',           'http://hi5.com/friend/profile/displayProfile.do?userid=%s'),
	'jaiku'       => array('Jaiku',         'http://%s.jaiku.com/'),
	'lastfm'      => array('Last.fm',       'http://www.last.fm/user/%s/'),
	'linkedin'    => array('LinkedIn',      'http://www.linkedin.com/in/%s'),
	'lj'          => array('LiveJournal',   'http://%s.livejournal.com/'),
	'mog'         => array('MOG',           'http://mog.com/%s'),
	'multiply'    => array('Multiply',      'http://%s.multiply.com/'),
	'myspace'     => array('MySpace',       'http://www.myspace.com/%s'),
	'newsvine'    => array('Newsvine',      'http://%s.newsvine.com/'),
	'ning'        => array('Ning',          'http://%s.ning.com/'),
	'orkut'       => array('Orkut',         'http://www.orkut.com/Profile.aspx?uid=%s'),
	'pandora'     => array('Pandora',       'http://pandora.com/people/%s'),
	'pownce'      => array('Pownce',        'http://pownce.com/%s/'),
	'reddit'      => array('Reddit',        'http://reddit.com/user/%s/'),
	'sonicliving' => array('SonicLiving',   'http://www.sonicliving.com/user/%s/'),
	'stumbleupon' => array('StumbleUpon',   'http://%s.stumbleupon.com/'),
	'tabblo'      => array('Tabblo',        'http://www.tabblo.com/studio/person/%s/'),
	'tagworld'    => array('TagWorld',      'http://www.tagworld.com/%s'),
	'technorati'  => array('Technorati',    'http://technorati.com/people/technorati/%s'),
	'tribe'       => array('Tribe',         'http://people.tribe.net/%s'),
	'twitter'     => array('Twitter',       'http://twitter.com/%s'),
	'upcoming'    => array('Upcoming',      'http://upcoming.yahoo.com/user/%s'),
	'vox'         => array('Vox',           'http://%s.vox.com/'),
	'wordpress'   => array('WordPress.com', 'http://%s.wordpress.com/'),
	'youtube'     => array('YouTube',       'http://www.youtube.com/user/%s'),
	'zooomr'      => array('Zooomr',        'http://www.zooomr.com/photos/%s')
);
ksort($social_networks);
?>